name: umedmiscanner
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  permission_handler: ^3.0.0
  shared_preferences: ^0.4.2
  connectivity: ^0.4.5+3
  http: ^0.12.0+2
  rxdart: ^0.22.0
  font_awesome_flutter: ^8.8.1
  flutter_spinkit: ^4.1.0
  flutter_launcher_icons: ^0.7.3
  toast: ^0.1.5
  circular_check_box: ^1.0.1
  curved_navigation_bar: ^0.3.2
  fancy_bottom_navigation: ^0.3.2
  flutter_calendar_carousel: ^1.4.11
  local_auth:
  calendar_strip: ^1.0.6
  dotted_border: ^1.0.5
  flutter_rating: ^0.0.2
  pin_code_fields: ^2.5.1
  provider: ^2.0.0
  image_picker: ^0.6.5+2
  network: ^0.7.0
  flutter_slidable: ^0.4.7
  flutter_datetime_picker: ^1.3.8
  speech_recognition: ^0.3.0+1
  permissions_plugin: ^1.1.4
  url_launcher: ^5.4.10
  bubble_tab_indicator: ^0.1.4
  fl_chart: ^0.9.4
  firebase_auth: ^0.16.1
  intl_phone_number_input: ^0.4.6+2
  expandable: ^4.1.3
  percent_indicator: ^2.1.5
  smooth_star_rating: ^1.1.1
  flutter_anywhere_menus: ^0.1.2
  date_picker_timeline: ^1.2.0
  flutter_time_picker_spinner: ^1.0.6+1
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.5.4
  linkedin_login: ^1.2.2
  flutter_switch: ^0.1.2
  sliding_sheet: ^0.4.0
  expand_widget: ^1.0.0+2
  flutter_svg: ^0.19.0
  flutter_dropdown: ^0.0.8
  flutter_image_editor: ^1.2.0
  image_crop: ^0.3.3
  image: ^2.1.18
  path_provider: ^1.6.18
  exif: ^1.0.3
  flutter_image_gallery: ^1.0.6
  numberpicker:
  image_cropper: ^1.3.1
  path: ^1.7.0
  torch_compat: ^1.0.2
  camerakit: ^0.0.46
  flutter_torch: ^0.2.3
  flutter_isolate: ^1.0.0+14
  flutter_better_camera: ^0.6.1
  video_player: ^0.11.0
  flutter_xlider: ^3.4.0
  dio: ^3.0.10
  clipboard: ^0.1.2+5
  image_downloader: ^0.20.1
  network_to_file_image: ^2.3.6
  searchable_dropdown: ^1.1.3
  skeleton_text: ^1.0.0
  carousel_slider: ^1.3.0
  flutter_image_compress: ^0.7.0
  multi_image_picker: ^4.7.14
  sleek_circular_slider: ^1.2.0+web
  flutter_sparkline: ^0.1.0
  fdottedline: ^1.0.1
  custom_switch_button: ^0.5.0


  flutter_native_image:
  cached_network_image:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "images/logo.png"
  image_path_android: "images/logo.png"
  image_path_ios: "images/logo.jpg"
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:

    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Gilroy-ExtraBold
      fonts:
        - asset: assets/fonts/Gilroy-ExtraBold.otf

    - family: GilroyLight
      fonts:
        - asset: assets/fonts/Gilroy-Light.otf

    - family: Gilroy-UltraLight
      fonts:
        - asset: assets/fonts/Gilroy-UltraLight.ttf

    - family: Gilroy-semi
      fonts:
        - asset: assets/fonts/Gilroy-semi.ttf

    - family: Gilroy-m
      fonts:
        - asset: assets/fonts/Gilroy-m.ttf

    - family: CloseIcon
      fonts:
        - asset: assets/fonts/CloseIcon.ttf

    - family: DoctorIcon
      fonts:
        - asset: assets/fonts/DoctorIcon.ttf


    - family: PaymentIcon
      fonts:
        - asset: assets/fonts/PaymentIcon.ttf

    - family: TicIcon
      fonts:
        - asset: assets/fonts/TicIcon.ttf


    - family: Arial-bold
      fonts:
        - asset: assets/fonts/arial-bold.ttf

    - family: AppointIcon
      fonts:
        - asset: assets/fonts/AppointIcon.ttf

    - family: ValidateIcon
      fonts:
        - asset: assets/fonts/ValidateIcon.ttf

    - family: CoinsIcon
      fonts:
        - asset: assets/fonts/CoinsIcon.ttf

    - family: AttachIcon
      fonts:
        - asset: assets/fonts/AttachIcon.ttf


    - family: ImagesIcon
      fonts:
        - asset: assets/fonts/ImagesIcon.ttf


    - family: DeteteIcon
      fonts:
        - asset: assets/fonts/DeteteIcon.ttf

    - family: UdIcon
      fonts:
        - asset: assets/fonts/UdIcon.ttf

    - family: CashIcon
      fonts:
        - asset: assets/fonts/CashIcon.ttf

    - family: FIcon
      fonts:
        - asset: assets/fonts/FIcon.ttf

    - family: Documentcon
      fonts:
        - asset: assets/fonts/Documentcon.ttf

    - family: DoneIcon
      fonts:
        - asset: assets/fonts/DoneIcon.ttf


    - family: Gilroy-Bold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf

    - family: Gilroy-SemiBold
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf

    - family: Gilroy-Medium
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf

    - family:  Gilroy-Regular
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf

    - family: PatientIcon
      fonts:
        - asset: assets/fonts/PatientIcon.ttf

    - family: SharePurpleIcon
      fonts:
        - asset: assets/fonts/SharePurpleIcon.ttf

    - family: WomanIcon
      fonts:
        - asset: assets/fonts/WomanIcon.ttf

    - family: InsuredIcon
      fonts:
       - asset: assets/fonts/InsuredIcon.ttf

    - family: DiabetesIcon
      fonts:
         - asset: assets/fonts/DiabetesIcon.ttf

    - family: PharmacyIcon
      fonts:
        - asset: assets/fonts/PharmacyIcon.ttf

    - family: FemaleIcon
      fonts:
       - asset: assets/fonts/FemaleIcon.ttf

    - family: StethIcon
      fonts:
        - asset: assets/fonts/StethIcon.ttf

    - family: DocIcon
      fonts:
         - asset: assets/fonts/DocIcon.ttf

    - family: IntervisionIcon
      fonts:
        - asset: assets/fonts/IntervisionIcon.ttf

    - family: ReferIcon
      fonts:
         - asset: assets/fonts/ReferIcon.ttf

    - family: ReportIcon
      fonts:
        - asset: assets/fonts/ReportIcon.ttf

    - family: ScanIcon
      fonts:
          - asset: assets/fonts/ScanIcon.ttf

    - family: IDNIcon
      fonts:
        - asset: assets/fonts/IDNIcon.ttf

    - family: CloseIcon
      fonts:
        - asset: assets/fonts/CloseIcon.ttf

    - family: YearsIcon
      fonts:
        - asset: assets/fonts/YearsIcon.ttf

    - family: MaleIcon
      fonts:
        - asset: assets/fonts/MaleIcon.ttf

    - family: CommentIcon
      fonts:
        - asset: assets/fonts/CommentIcon.ttf

    - family: MicroIcon
      fonts:
        - asset: assets/fonts/MicroIcon.ttf

    - family: XRayIcon
      fonts:
        - asset: assets/fonts/XRayIcon.ttf

    - family: PulseIcon
      fonts:
        - asset: assets/fonts/PulseIcon.ttf






  assets:
    - assets/locale_en.json
    - assets/locale_ar.json
    - images/
    - images/id_scan_border.png
    - images/profile_image.jpg
    - images/egypt.png
    - images/heart.svg
    - images/consultation.svg
    - images/diabetes.svg
    - images/drug.svg
    - images/Flat.svg
    - images/Group.svg
    - images/height.png
    - images/hypertension.svg
    - images/medical-prescription.svg
    - images/add.svg
    - images/heart-attack.svg
    - images/heartdot.svg
    - images/Lungs.svg
    - images/thermometers.svg
    - images/blood-pressure-gauge.svg
    - images/electrocardiogram.svg
    - images/heartrate.svg
    - images/shield.svg
    - images/surface1.svg
    - images/flat.svg
    - images/fitness.svg
    - images/bmi.svg
    - images/doctor.svg
    - images/mental-health.svg
    - images/doctor_profile.jpg
    - images/teeth.svg
    - images/brain.svg
    - images/pediatrician.svg
    - images/pressure.svg
    - images/prescriptions.jpeg
    - images/medical-record.svg