/// Flutter icons AttachIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AttachIcon
///      fonts:
///       - asset: fonts/AttachIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AttachIcon {
  AttachIcon._();

  static const _kFontFam = 'AttachIcon';
  static const _kFontPkg = null;

  static const IconData attach = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
