/// Flutter icons CashIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CashIcon
///      fonts:
///       - asset: fonts/CashIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CashIcon {
  CashIcon._();

  static const _kFontFam = 'CashIcon';
  static const _kFontPkg = null;

  static const IconData funds = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
