/// Flutter icons CoinsIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CoinsIcon
///      fonts:
///       - asset: fonts/CoinsIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CoinsIcon {
  CoinsIcon._();

  static const _kFontFam = 'CoinsIcon';
  static const _kFontPkg = null;

  static const IconData coin_stack = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
