/// Flutter icons DeteteIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DeteteIcon
///      fonts:
///       - asset: fonts/DeteteIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DeteteIcon {
  DeteteIcon._();

  static const _kFontFam = 'DeteteIcon';
  static const _kFontPkg = null;

  static const IconData delete = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
