/// Flutter icons Documentcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Documentcon
///      fonts:
///       - asset: fonts/Documentcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Documentcon {
  Documentcon._();

  static const _kFontFam = 'Documentcon';
  static const _kFontPkg = null;

  static const IconData document = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
