/// Flutter icons FIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FIcon
///      fonts:
///       - asset: fonts/FIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FIcon {
  FIcon._();

  static const _kFontFam = 'FIcon';
  static const _kFontPkg = null;

  static const IconData amany = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
