/// Flutter icons ImagesIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ImagesIcon
///      fonts:
///       - asset: fonts/ImagesIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ImagesIcon {
  ImagesIcon._();

  static const _kFontFam = 'ImagesIcon';
  static const _kFontPkg = null;

  static const IconData gallery = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
