/// Flutter icons TicIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TicIcon
///      fonts:
///       - asset: fonts/TicIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TicIcon {
  TicIcon._();

  static const _kFontFam = 'TicIcon';
  static const _kFontPkg = null;

  static const IconData subscription_ticket__1_ = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
