/// Flutter icons UdIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  UdIcon
///      fonts:
///       - asset: fonts/UdIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class UdIcon {
  UdIcon._();

  static const _kFontFam = 'UdIcon';
  static const _kFontPkg = null;

  static const IconData udemilogo = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
