/// Flutter icons ValidateIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ValidateIcon
///      fonts:
///       - asset: fonts/ValidateIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ValidateIcon {
  ValidateIcon._();

  static const _kFontFam = 'ValidateIcon';
  static const _kFontPkg = null;

  static const IconData validation = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
