/// Flutter icons CloseIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CloseIcon
///      fonts:
///       - asset: fonts/CloseIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CloseIcon {
  CloseIcon._();

  static const _kFontFam = 'CloseIcon';
  static const _kFontPkg = null;

  static const IconData close = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
