/// Flutter icons DiabetesIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DiabetesIcon
///      fonts:
///       - asset: fonts/DiabetesIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DiabetesIcon {
  DiabetesIcon._();

  static const _kFontFam = 'DiabetesIcon';
  static const _kFontPkg = null;

  static const IconData diabetes = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
