/// Flutter icons DoctorIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DoctorIcon
///      fonts:
///       - asset: fonts/DoctorIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DoctorIcon {
  DoctorIcon._();

  static const _kFontFam = 'DoctorIcon';
  static const _kFontPkg = null;

  static const IconData doctor = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
