/// Flutter icons IDNIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IDNIcon
///      fonts:
///       - asset: fonts/IDNIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IDNIcon {
  IDNIcon._();

  static const _kFontFam = 'IDNIcon';
  static const _kFontPkg = null;

  static const IconData id = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
