/// Flutter icons InsuredIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  InsuredIcon
///      fonts:
///       - asset: fonts/InsuredIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class InsuredIcon {
  InsuredIcon._();

  static const _kFontFam = 'InsuredIcon';
  static const _kFontPkg = null;

  static const IconData insured = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
