/// Flutter icons IntervisionIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IntervisionIcon
///      fonts:
///       - asset: fonts/IntervisionIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IntervisionIcon {
  IntervisionIcon._();

  static const _kFontFam = 'IntervisionIcon';
  static const _kFontPkg = null;

  static const IconData intervention = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
