/// Flutter icons MaleIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MaleIcon
///      fonts:
///       - asset: fonts/MaleIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MaleIcon {
  MaleIcon._();

  static const _kFontFam = 'MaleIcon';
  static const _kFontPkg = null;

  static const IconData man = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
