/// Flutter icons MicroIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MicroIcon
///      fonts:
///       - asset: fonts/MicroIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MicroIcon {
  MicroIcon._();

  static const _kFontFam = 'MicroIcon';
  static const _kFontPkg = null;

  static const IconData microscope = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
