/// Flutter icons PatientIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PatientIcon
///      fonts:
///       - asset: fonts/PatientIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PatientIcon {
  PatientIcon._();

  static const _kFontFam = 'PatientIcon';
  static const _kFontPkg = null;

  static const IconData patientinfo = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
