/// Flutter icons PharmacyIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PharmacyIcon
///      fonts:
///       - asset: fonts/PharmacyIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PharmacyIcon {
  PharmacyIcon._();

  static const _kFontFam = 'PharmacyIcon';
  static const _kFontPkg = null;

  static const IconData pharmacy = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
