/// Flutter icons PulseIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PulseIcon
///      fonts:
///       - asset: fonts/PulseIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PulseIcon {
  PulseIcon._();

  static const _kFontFam = 'PulseIcon';
  static const _kFontPkg = null;

  static const IconData pulse_line = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
