/// Flutter icons ReferIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ReferIcon
///      fonts:
///       - asset: fonts/ReferIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ReferIcon {
  ReferIcon._();

  static const _kFontFam = 'ReferIcon';
  static const _kFontPkg = null;

  static const IconData referral = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
