/// Flutter icons ReportIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ReportIcon
///      fonts:
///       - asset: fonts/ReportIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ReportIcon {
  ReportIcon._();

  static const _kFontFam = 'ReportIcon';
  static const _kFontPkg = null;

  static const IconData report = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
