/// Flutter icons ScanIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ScanIcon
///      fonts:
///       - asset: fonts/ScanIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ScanIcon {
  ScanIcon._();

  static const _kFontFam = 'ScanIcon';
  static const _kFontPkg = null;

  static const IconData scan = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
