/// Flutter icons StethIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  StethIcon
///      fonts:
///       - asset: fonts/StethIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class StethIcon {
  StethIcon._();

  static const _kFontFam = 'StethIcon';
  static const _kFontPkg = null;

  static const IconData stethoscope__1_ = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
