/// Flutter icons WomanIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WomanIcon
///      fonts:
///       - asset: fonts/WomanIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WomanIcon {
  WomanIcon._();

  static const _kFontFam = 'WomanIcon';
  static const _kFontPkg = null;

  static const IconData woman = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
