/// Flutter icons XRayIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  XRayIcon
///      fonts:
///       - asset: fonts/XRayIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class XRayIcon {
  XRayIcon._();

  static const _kFontFam = 'XRayIcon';
  static const _kFontPkg = null;

  static const IconData x_ray = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
